### ISSUE TITLE
Serpent 1.30 does not work with Python 2.7

### ISSUE THREAD

**Issue by EricSalemi** [irmen/Serpent#36] opened 2020-02-28 13:40 UTC
Yesterday our production codebase started to fail:

21:17:52.932 	DEBUG 	[ PIXIE ] Traceback (most recent call last): 	
21:17:52.932 	DEBUG 	[ PIXIE ]   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main 	
21:17:52.933 	DEBUG 	[ PIXIE ]     "__main__", fname, loader, pkg_name) 	
21:17:52.933 	DEBUG 	[ PIXIE ]   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code 	
21:17:52.934 	DEBUG 	[ PIXIE ]     exec code in run_globals 	
21:17:52.934 	DEBUG 	[ PIXIE ]   File "/home/pi/workspace/septentrio/pixie.py", line 25, in <module> 	
21:17:52.935 	DEBUG 	[ PIXIE ]     import serpent 	
21:17:52.935 	DEBUG 	[ PIXIE ]   File "/usr/local/lib/python2.7/dist-packages/serpent.py", line 56, in <module> 	
21:17:52.936 	DEBUG 	[ PIXIE ]     from collections.abc import KeysView, ValuesView, ItemsView 	
21:17:52.936 	DEBUG 	[ PIXIE ] ImportError: No module named abc

Turns out serpent is trying to import collections.abc which does not exist in Python 2.7.

Is this a bug?

**Comment by EricSalemi** [comment] 2020-02-28 13:49
It got installed as a dependency of Pyro==4.72.

Should I file a bug on Pyro4 instead?

**Comment by irmen** [comment] 2020-02-28 18:19
This is by design. See the readme. Python 2.7 is officially end of life by the PSF now so I decided to leave it behind permanently.
Either force install a previous serpent version or install the latest pyro4 version, where the serpent dependency should be fixed.

**Closed by irmen** 2020-02-28 18:19 UTC

**Comment by irmen** [comment] 2020-03-01 01:48
(or better yet, update to python 3)

**Comment by EricSalemi** [comment] 2020-03-02 12:03
Update to Python 3.x is underway for more than a year :(

Fixing Pyro4 to version 4.79 solves the issue.

**Comment by irmen** [comment] 2020-03-04 20:52
Ooh, you must have a large system then... I hope it's going well.
Glad you were able to solve the dependency issue by updating Pyro4 itself, in the meantime!
